version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: '${{secrets.DEPENDABOT_TOKEN}}'
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
    open-pull-requests-limit: 10
    target-branch: master
    ignore:
      - dependency-name: vue2-datepicker
        versions:
          - '> 2.12.0'
      - dependency-name: '@typescript-eslint/eslint-plugin'
        versions:
          - '> 3.5.0'
      - dependency-name: '@vue/cli-plugin-eslint'
        versions:
          - '> 4.4.6'
    registries:
      - npm-registry-npm-pkg-github-com